sensebox/openSenseMap

app/index.html

This fixes both #53 and #50. For me, this works with `grunt serve`. I did not test `grunt build`

move bootstrap css out of bowerinstall definition

---

app/index.html
app/scripts/app.js
app/scripts/controllers/header.js
app/scripts/controllers/map.js
app/scripts/controllers/sidebar.boxdetails.js
app/translations/de_DE.json
app/translations/en_US.json

- improve marker focusing by considering the sidebar width
- fix language selection on pageload
- show active senseboxes (green markers) on top of inactive ones (fixes #84)

minor fixes (branch center-map)

---

app/index.html
app/styles/main.css

* removing openSenseMap text on small screens

optimize for mobile

---

app/translations/en_US.json

The "phenomeon" word was updated to "phenomenon"

The "phenomeon" word is misspelled.

---

app/scripts/controllers/sidebar.boxdetails.js

refresh measurements of selected box every minute

get new measurements every minute

---

Gruntfile.js
app/index.html
app/scripts/controllers/editbox.js
app/scripts/controllers/header.js
app/scripts/controllers/map.js
app/scripts/controllers/register.js
app/scripts/controllers/sidebar.boxdetails.js
app/scripts/services/filters.js
app/scripts/services/osemdata.js
app/styles/main.css
app/translations/de_DE.json
app/translations/en_US.json
app/views/search.html
app/views/search.item.html

In this pull request, a search component is integrated.
This is WIP. Do not merge!
These points are planned:

[WIP] search component :mag:

---

app/views/explore2.sidebar.download.html

Show only phenomenons of filtered boxes.

only show phenomenons of filtered boxes closes #152

---

app/scripts/controllers/sidebar.interpolation.js
app/views/explore2.sidebar.interpolation.html

fix interpolation power and input element is readonly

change interpolation power input element, fixes #156

---

app/index.html
app/scripts/controllers/header.js

This PR adds the measurements per minute as a mouseover in the title bar.
One can see the current measurements per minute by hovering the mouse cursor over the count of measurements.

include measurements per minute

---

app/scripts/controllers/map.js
app/views/explore2.map.html

fix marker labeling

---

app/views/editbox.html
app/views/register.html

Icon selection was not working. Dropdown menu was not shown.

fix icon selection during registration and editing

---

app/scripts/services/osemdata.js

This pull request changes the marker color of mobile boxes to blue

color mobile boxes in blue

---

app/components/leaflet.directive.js
app/components/leaflet.service.js
app/index.html
app/scripts/controllers/account.box.edit.sensors.js
app/scripts/controllers/account.dashboard.js
app/scripts/controllers/header.js
app/scripts/controllers/map.js
app/scripts/models/box.js
app/scripts/services/account.js
app/scripts/services/osemdata.js
app/styles/main.css
app/translations/de_DE.json
app/translations/en_US.json
app/views/account.dashboard.html
app/views/explore2.map.legend.html
app/views/explore2.sidebar.box.html
app/views/info.html

applies color coding for boxes throughout the application based on the box exposure type and its activity.
- box markers
- circle marker rings
- dashboard background
shall we keep the special rocket icon for mobile boxes?

mobile boxes: color coding

---

app/scripts/controllers/account.dashboard.js
app/styles/main.css
app/views/account.dashboard.html

This pull request is a fix for #250 
It introduces a toggle button to switch between the current card view and a list view

Dashboard list toggle

---

app/views/account.box.register.html
package-lock.json
package.json

New version of translation fixes typos

fix(registration): Update translation package

---

app/components/clipboard.directive.js

Add different methods to copy to clipboard for iOS and the res
fix #297

fix(clipboard): Fix copy to clipboard directive

---

app/views/account.box.edit.script.html
app/views/account.box.register.html

Do not autofill ssid and password fields if password is saved for website
fixes #295
Do not autofill `ssid` and `password` fields in edit section and registration.

fix(dashboard): Do not autofill ssid and password

---

app/scripts/controllers/register.js

Collapse all hardware section in registration step
closes #296
Collapse all accordions (hardware selection) in registration

refactor(registration): Collapse all hardware sections

---

app/views/account.box.register.html

add bme and smt to edu registration

---

app/views/account.dashboard.html

Fixes #333
- OS: macOS
- Browser & Version: Chrome

fix dead link closes #333

---

app/views/account.dashboard.html

Reverts sensebox/openSenseMap#334

Revert "fix dead link closes #333"

---

app/scripts/controllers/account.box.edit.script.js
app/scripts/controllers/register.js
app/views/account.box.edit.script.html
app/views/account.box.register.html
app/views/account.dashboard.html
package-lock.json
package.json

Add sound sensor

---

README.md
app/views/account.box.register.html

Add sensortype to box registration

---

app/scripts/controllers/register.js

This fixes #319 
New behaviour: Only change the grouptag of boxes to `edu` if the user hasn't entered something else. Only reset the grouptag to an empty string if it was set to `edu` before
ping @synolus-david does this fix your issue?

only set box tag to 'edu' if no other tag has been set

---

app/index.html

|before|after|
|-|-|
|<img width="379" alt="Bildschirmfoto 2020-03-04 um 11 52 42" src="https://user-images.githubusercontent.com/12086004/75872644-d7206900-5e0e-11ea-89c2-ff6c32e6de4e.png">|<img width="382" alt="Bildschirmfoto 2020-03-04 um 11 52 54" src="https://user-images.githubusercontent.com/12086004/75872663-dd164a00-5e0e-11ea-84af-dff27aaed55f.png">|

fix z-index for cookie consent banner

---

app/views/account.box.register.html

fix windspeed template naming

---

app/scripts/controllers/sidebar.download.js
app/scripts/services/opensensemapapi.js

encode URI just once fixes #355

---

CHANGELOG.md
app/scripts/controllers/sidebar.download.js
app/scripts/services/opensensemapapi.js
bower.json
package-lock.json
package.json

Encode URL just once

---

app/scripts/controllers/account.box.edit.ttn.js
app/scripts/controllers/register.js
app/views/account.box.edit.ttn.html
app/views/account.box.register.html

Adding Cayenne LPP Decoding (https://github.com/sensebox/ttn-osem-integration/tree/cayenne)

Cayenne LPP Decoding

---

app/views/account.box.register.html

Fixes issue that you can not register a new senseBox:edu

fix registration error

---

CHANGELOG.md
app/components/leaflet.directive.js
bower.json
package-lock.json
package.json

Preparation for modern mapbox tiles

---

.github/workflows/build.yaml

Use production maptiles on release

use prod maptiles on release

---

.github/workflows/build.yaml
README.md

This PR removes mentions of the development branch. master is now development

Remove mentions of development branch

---

.github/workflows/build.yaml

Push container image to hub also on published release in CI

---

.github/workflows/build.yaml

bump package.json version on release

---

.github/workflows/build.yaml

undo Bump package.json version

---

.eslintignore
.eslintrc.js
.github/workflows/build.yaml
app/scripts/app.js
app/scripts/controllers/account.box.edit.security.js
app/scripts/controllers/account.box.edit.sensors.js
app/scripts/controllers/account.box.edit.ttn.js
app/scripts/controllers/help.js
app/scripts/controllers/register.js
app/scripts/controllers/sidebar.error.js
app/scripts/services/authenticationInterceptor.js
app/scripts/services/helpmodal.js
app/scripts/services/opensensemapapi.js

Enable linting using eslint in ci
https://github.com/sensebox/openSenseMap/pull/390/commits/109b0d51ef2ca40a2ac0c2207ef0dc04cd27c541 contains automatic fixes
https://github.com/sensebox/openSenseMap/pull/390/commits/f684f9fd729582000f82793aafff95c91df843b8 contains manual fixes by me
I've skimmed the deploy preview and everything seems to be working

Enable linting

---

app/views/info.faq.html

Together with changing links to target="_blank" this should fix #392

add 'allow-popups' to sandbox attribute in faq view

---

.github/workflows/build.yaml
app/scripts/services/donationmodal.js
package-lock.json
package.json

fix(date error for donation modal):

---

.github/workflows/build.yaml
Gruntfile.js
app/index.html
app/scripts/constants.js
package-lock.json
package.json

Set version in `package.json` according to tag on releasing a new version.
Build process uses the `version` field from `package.json` to set Version on the `About` page.

ci(Release): Set correct version in package.json

---

Gruntfile.js
app/views/donation.html
app/views/donors.html

Link was still pointing to Uni Münster donation page.
Changed it to betterplace.

Fix donation links

---

app/index.html
app/scripts/controllers/account.box.edit.ttn.js
app/scripts/controllers/register.js
app/scripts/models/box.js
app/views/account.box.edit.ttn.html

With this change it is possible to select the `Cayenne` profile after registration of a new device and change the decoding options.
What´s missing (WIP):

Cayenne TTN profile

---

app/scripts/controllers/account.box.dataupload.js
app/views/account.box.dataupload.html
bower.json

add logging to upload

---

app/index.html
app/scripts/controllers/header.js
app/styles/main.css
bower.json

Beta banner

---

.github/workflows/build.yaml
.github/workflows/registry-pr-purge.yaml
.github/workflows/registry-purge.yaml
package-lock.json

Move to ghcr registry

---

app/components/leaflet.directive.js

Increase maxZoom level to better support selecting devices that are only a few meters apart
fix #436

fix(map): Increase maxZoom level

---

app/scripts/controllers/account.box.edit.script.js
app/views/account.box.register.html

Enable compilation for ethernet devices during registartion and editing steps
closes #438

refactor(device): Enable compilation for ethernet devices

---

app/scripts/controllers/register.js
app/views/account.box.register.html

New sensor for temperature and airpressure (DPS310) was added to registration.

feat(registration): Add new DPS310 sensor

---

app/components/charts.directive.js

Render chart correctly with just one datapoint
RIght now charts with just one datapoint are not rendered correctly. This fix will render also charts with just one datapoint.

Render chart with one datapoint

---

bower.json

build(dependencies): pin leaflet version

---

app/styles/main.css
app/views/donation.html

Add OpenStreetMap hint to popup (hint is included in `i18n` pacakge)

chore(translation): add OpenStreetMap hint

---

.github/workflows/build.yaml

chore(action): update github action dependencies

---

.github/workflows/build.yaml

fix(ci): set `provenance: false` on docker/build-push-action

---

app/components/leaflet.directive.html

We have to include the Maptiler logo.

Add maptiler logo

---

.github/workflows/build.yaml

Change tile style url to MapTiler

ci(actions): change tile style url

---

app/scripts/controllers/account.dashboard.js
app/scripts/services/account.js
app/views/account.dashboard.html

Add pagination controls to dashboard to paginate through boxes

feat(account): dashboard boxes pagination

---

app/views/account.box.register.html

Add new luftdaten templates based on SPS30, BME280 and SHTX3

chore(templates): add new luftdaten templates

---

app/scripts/controllers/account.box.edit.mqtt.js
app/views/account.box.edit.mqtt.html

Correctly validate MQTT integration Url

fix(edit): validate MQTT Integration url
